---
apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  labels:
    name: multi-pod
spec:
  containers:
  - name: beta
    image: busybox
    command: ["sleep"]
    args: ["4800"]
  - name: alpha
    image: nginx
