---
apiVersion: v1
kind: Namespace
metadata:
  name: finance-raz
---
apiVersion: v1
kind: Pod
metadata:
  name: temp-bus
  namespace: finance-raz
  labels:
spec:
  containers:
  - name: temp-bus
    image: redis:alpine
