---
apiVersion: v1
kind: apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 5  
  selector:
    matchLabels:
      app: myapp
      env: dev
  template:
    metadata:
      labels:
        app: myapp
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx
