apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod-raz
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging
  spec:
  selector:
    matchLabels:
      app: reddis
  replicas: 1
  template:
    metadata:
      labels:
        tier: msg
        app: reddis
    spec:
      containers:
      - name: reddis
        image: redis:alpine
        ports:
        - containerPort: 8080
