---
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
  - port: 50
    targetPort: 5050
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-resolver
  labels:
    name: busybox
    app: nginx
spec:
  containers:
    - name: nginx-resolver
      image: nginx
      ports:
      - containerPort: 50
